version: '3.2'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    # - CI=true
    # command: yarn test --ci
  frontend:
    build: .
    expose:
      - 3030
    ports:
      - 3030:3030
    command: /bin/sh -c "npm run start"
